// <auto-generated />
namespace MovieRent.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class SeedAdminAndRole : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedAdminAndRole));
        
        string IMigrationMetadata.Id
        {
            get { return "202012241643519_SeedAdminAndRole"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
